package com.nefu.spring.weather.entity;

public class WUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_user.user_id
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_user.user_name
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_user.password
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_user.user_id
     *
     * @return the value of w_user.user_id
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_user.user_id
     *
     * @param userId the value for w_user.user_id
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_user.user_name
     *
     * @return the value of w_user.user_name
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_user.user_name
     *
     * @param userName the value for w_user.user_name
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_user.password
     *
     * @return the value of w_user.password
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_user.password
     *
     * @param password the value for w_user.password
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }
}