package com.nefu.spring.weather.entity;

import java.math.BigDecimal;
import java.util.Date;

public class WWeather {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_weather.weather_id
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    private Long weatherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_weather.city_name
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    private String cityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_weather.weather_time
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    private Date weatherTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_weather.weather_1
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    private BigDecimal weather1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_weather.weather_2
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    private BigDecimal weather2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_weather.weather_3
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    private BigDecimal weather3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_weather.weather_4
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    private BigDecimal weather4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_weather.weather_5
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    private BigDecimal weather5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_weather.weather_6
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    private BigDecimal weather6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_weather.weather_7
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    private BigDecimal weather7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_weather.weather_8
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    private BigDecimal weather8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_weather.weather_9
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    private BigDecimal weather9;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_weather.weather_id
     *
     * @return the value of w_weather.weather_id
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    public Long getWeatherId() {
        return weatherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_weather.weather_id
     *
     * @param weatherId the value for w_weather.weather_id
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    public void setWeatherId(Long weatherId) {
        this.weatherId = weatherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_weather.city_name
     *
     * @return the value of w_weather.city_name
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_weather.city_name
     *
     * @param cityName the value for w_weather.city_name
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_weather.weather_time
     *
     * @return the value of w_weather.weather_time
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    public Date getWeatherTime() {
        return weatherTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_weather.weather_time
     *
     * @param weatherTime the value for w_weather.weather_time
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    public void setWeatherTime(Date weatherTime) {
        this.weatherTime = weatherTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_weather.weather_1
     *
     * @return the value of w_weather.weather_1
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    public BigDecimal getWeather1() {
        return weather1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_weather.weather_1
     *
     * @param weather1 the value for w_weather.weather_1
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    public void setWeather1(BigDecimal weather1) {
        this.weather1 = weather1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_weather.weather_2
     *
     * @return the value of w_weather.weather_2
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    public BigDecimal getWeather2() {
        return weather2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_weather.weather_2
     *
     * @param weather2 the value for w_weather.weather_2
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    public void setWeather2(BigDecimal weather2) {
        this.weather2 = weather2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_weather.weather_3
     *
     * @return the value of w_weather.weather_3
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    public BigDecimal getWeather3() {
        return weather3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_weather.weather_3
     *
     * @param weather3 the value for w_weather.weather_3
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    public void setWeather3(BigDecimal weather3) {
        this.weather3 = weather3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_weather.weather_4
     *
     * @return the value of w_weather.weather_4
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    public BigDecimal getWeather4() {
        return weather4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_weather.weather_4
     *
     * @param weather4 the value for w_weather.weather_4
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    public void setWeather4(BigDecimal weather4) {
        this.weather4 = weather4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_weather.weather_5
     *
     * @return the value of w_weather.weather_5
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    public BigDecimal getWeather5() {
        return weather5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_weather.weather_5
     *
     * @param weather5 the value for w_weather.weather_5
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    public void setWeather5(BigDecimal weather5) {
        this.weather5 = weather5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_weather.weather_6
     *
     * @return the value of w_weather.weather_6
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    public BigDecimal getWeather6() {
        return weather6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_weather.weather_6
     *
     * @param weather6 the value for w_weather.weather_6
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    public void setWeather6(BigDecimal weather6) {
        this.weather6 = weather6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_weather.weather_7
     *
     * @return the value of w_weather.weather_7
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    public BigDecimal getWeather7() {
        return weather7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_weather.weather_7
     *
     * @param weather7 the value for w_weather.weather_7
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    public void setWeather7(BigDecimal weather7) {
        this.weather7 = weather7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_weather.weather_8
     *
     * @return the value of w_weather.weather_8
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    public BigDecimal getWeather8() {
        return weather8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_weather.weather_8
     *
     * @param weather8 the value for w_weather.weather_8
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    public void setWeather8(BigDecimal weather8) {
        this.weather8 = weather8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_weather.weather_9
     *
     * @return the value of w_weather.weather_9
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    public BigDecimal getWeather9() {
        return weather9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_weather.weather_9
     *
     * @param weather9 the value for w_weather.weather_9
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    public void setWeather9(BigDecimal weather9) {
        this.weather9 = weather9;
    }
}