package com.nefu.spring.weather.mapper;

import com.nefu.spring.weather.entity.WUser;
import java.util.List;

public interface WUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_user
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_user
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    int insert(WUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_user
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    WUser selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_user
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    List<WUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_user
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    int updateByPrimaryKey(WUser record);

    WUser selectByName(String userName);
}