package com.nefu.spring.weather.mapper;

import com.nefu.spring.weather.entity.WWeather;
import java.util.List;

public interface WWeatherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_weather
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Long weatherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_weather
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    int insert(WWeather record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_weather
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    WWeather selectByPrimaryKey(Long weatherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_weather
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    List<WWeather> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_weather
     *
     * @mbg.generated Thu Mar 26 23:40:07 GMT+08:00 2020
     */
    int updateByPrimaryKey(WWeather record);
}